server:
  port: 8083
spring:
  application:
    name: provider001-8083
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: zqh123123123
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.200:7071,192.168.20.200:7073,192.168.20.200:7075
mybatis:
  mapper-locations: classpath:mapper/*.xml
